##########
### Start
##########

# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        /:categories/:title.html

# Setup
excerpt_separator: "</strong>"
title:            Emacs Online Documentation
tagline:          'An up-to-date online documentation of ALL Emacs functions and variables.'
url:              'http://doc.endlessparentheses.com'

baseurl:          /
author:
  name:           Artur Malabarba
  url:            https://github.com/Bruce-Connor
  email:          bruce.connor.am@gmail.com
  twitter:        https://twitter.com/AMalabarba

# Content
timezone:         UTC
future:           false

# This doesn't work, had to implement my own solution.
# lsi:              true

pages_list:
  About: ['/about.html', '/icons/favicon-bw.png']
  Archive: ['/archive.html', '/icons/envelope.png']
  RSS Feed: ['/atom.xml', '/icons/rss.png']
  Tag List: ['/tags.html', '/icons/tag.png']
  Android App: ['http://doc.endlessparentheses.com/app.html', '/icons/android.png']

gems:
  - jekyll-sitemap

